package mvc;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;    
     
        //verificando funcionamiento
        //21:10
  
    }
}
