/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;    
     
        //comentario
        //verificar cambios
        //20:49
  
    }
}
