/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;    
        //hola como andas
        ///hola me pueden leer???
        // soy saul
        // comentario
        
    }
}
